# -*- coding: utf-8 -*-
"""DataType.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYbrpREDSOsE0TJ3ne-HDoqhMT-_GT1X
"""

#Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.
list1=["M", "na", "i", "Ra"]
list2=["y", "me", "s", "hul"]
lst=[]
for i in range(min(len(list1),len(list2))):
  pair=list1[1],list2[i]
  lst.append(pair)
print(lst)

#2.Write a program to add item 7000 after 6000 in the following Python List
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
lst=list1[2][2].append(7000)
print(list1)

#3.Write a program to show no. of items of each candy type.
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]
for i in range(min(len(candy_list), len(no_of_items))):
  print(candy_list[i],"-", no_of_items[i])

#4.Running Sum on list Write a program to print a list after performing running sum on it.
list1 = [1,2,3,4,5,6]
sum=0
ls=[]
for i in range(len(list1)):
  sum+=list1[i]
  ls.append(sum)
print(ls)

#5. You are given a list of integers. You are asked to make a list by running through elements of the list by adding all elements greater and itself.
list1=[2,4,6,10,1]
lst=[]
for i in range(len(list1)):
  total=0
  for j in range(len(list1)):
    if list1[j]>list1[i]:
      total+=list1[j]
  total+=list1[i]
  lst.append(total)
print(lst)

#6. Find list of common unique items from two list. and show in increasing order
num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
comm=list(set(num1) & set(num2))
print(comm)

#7.Sort a list of alphanumeric strings based on product value of numeric character in it. If in any string there is no numeric character take it's product value as 1.
list1=['1ac21', '23fg', '456', '098d','1','kls']
def product_digit(s):
  product=1
  has_digit=False
  for i in s:
    if s.isdigit():
      product*=int(i)
      has_digit=True
    if not has_digit:
      product=1
    return product
sorted_lst=sorted(list1,key=product_digit , reverse=True)
print(sorted_lst)

#8. Write a program that can find the max number of each row of a matrix
def find_max(list1):
  lst=[]
  for i in list1:
    lst.append(max(i))
  print(lst)

list1=[[1,2,3],[4,5,6],[7,8,9]]
find_max(list1)

#9. Shortlist Students for a Job role Ask user to input students record and store in tuples for each record. Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.
n=int(input("Enter No of recors: "))
students=()
for i in range(1,n+1):
  print(f"Enter Details of student- {i}")
  name = input("Enter student name: ")
  education=input("Enter Higher Education: ")
  skill = input("Enter Primary skill: ")
  year = int(input("Enter year of graduation: "))

  students=students+((name,education,skill,year),)

print("\n Enter job Role Requirement")
req_skill = input("Enter skill: ")
req_education =input("Enter Higher Education: ")
req_year = int(input("Enter year of graduation: "))

found = False
for student in students:
  if student[1]==req_education and student[2]==req_skill and student[3]==req_year:
    found=True
    print(student)


if not found:
   print("No such Dictionary")

#.10 Write a program to find set of common elements in three lists using sets.
def common(ar1,ar2,ar3):
  common=list(set(ar1) & set(ar2) & set(ar3))
  print(common)

ar1 = [1, 5, 10, 20, 40, 80]
ar2 = [6, 7, 20, 80, 100]
ar3 = [3, 4, 15, 20, 30, 70, 80, 120]
common(ar1,ar2,ar3)

#11.Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.
str1="hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
vowel="aeiouAEIOU"
count=set()
for i in str1:
  if i in vowel:
    count.add(i)
print(len(count))

#12.Intersection of two lists. Intersection of two list means we need to take all those elements which are common to both of the initial lists and store them into another list. Only use using list-comprehension.
def inte(lst1,lst2):
  comm=[i for i in lst1  if i in lst2]
  print(comm)
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
inte(lst1,lst2)


def intte(list1,list2):
  common=[x for x in list1 if x in list2]
  print(common)

list1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
list2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
intte(list1,list2)

#13.Convert a list of Tuples into Dictionary.
def Convert(list1):
  sett={}
  for key,value in list1:
    sett[key]=[value]
  print(sett)
list1=[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
Convert(list1)

def con(list2):
  my_dictionary={}
  for key,value in list2:
     my_dictionary[key]=[value]
  print(my_dictionary)

list2=[('A',1),('B',2),('C',3),('D',4)]
con(list2)

#14.Write a Python function that takes a list and returns a new list with unique elements of the first list.
def unique_number(list1):
  uniq=list(set(list1))
  print(uniq)

list1=[1,2,3,3,3,3,4,5]
unique_number(list1)

#15.Write a Python program to print the even numbers from a given list.
def even_number(Sample_List):
  lsit1=[]
  for i in Sample_List:
    if i%2==0:
      lsit1.append(i)
  print(lsit1)

Sample_List = [1, 2, 3, 4, 5, 6, 7, 8, 9]
even_number(Sample_List)

#16.Write a Python function to check whether a number is perfect or not.¶
#A Perfect number is a number that is half the sum of all of its positive divisors (including itself).
def suma(num):

  sum=0
  for i in range(1,num+1):
     if num%i==0:
       sum+=i
  if sum/2==num:
    print("Perfect number")
  else:
    print("Not a perfect number")
num=7
suma(num)

#17.Write a Python function to concatenate any no of dictionaries to create a new one.
def concanate(dic1,dic2,dic3):
  result={}
  for i in dic1:
    result[i]=dic1[i]
  for j in dic2:
    result[j]=dic2[j]
  for k in dic3:
    result[k]=dic3[k]
  print(result)
dic1={1:10, 2:20}
dic2={3:30, 4:40}
dic3={5:50,6:60}
concanate(dic1,dic2,dic3)

#18.Write a python function that receives a list of integers and prints out a histogram of bin size 10
def histo(list1):
    re={}
    for i in list1:
        start = (i // 10)*10+1
        end=start+9
        key =f"{start}-{end}"
        if key in re:
            re[key]+=1
        else:
             re[key]=1
    print(re)

list1=[13,42,15,37,22,39,41,50]
histo(list1)