# -*- coding: utf-8 -*-
"""Excepation_Handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeX_ZPMnYDZXvuG4gwpmNtqzv9meqfFn
"""

#1. Write a Python program to handle a ZeroDivisionError exception when dividing a number by zero.
try:
  divident=int(input("Enter a divident: "))
  divisor=int(input("Enter a divisor : "))
  division=divident/divisor
  print("Division is : ",division)
except ZeroDivisionError :
  print("dividing by Zero(0) can't be possiblr:")

from logging import exception
#2. Write a Python program that prompts the user to input an integer and raises a ValueError exception if the input is not a valid integer.
try:
   num1=int(input("Enter a first number:"  ))
   num2=int(input("Enter a second number:" ))
   add=num1+num2
   print("Addition is:", add)
except ValueError :
  print("it is not a valid integer:")

try:
  num=int(input("Enter a number:" ))
  if num%2==0:
    print("number is even")
  else:
    print("number is odd:")
except ValueError:
  print("input is not a valid integer")

#to write a file
try:
  with open("Sampal.csv",'w') as m:
    m.write("Hi i am learning a python \n now i am regularly practice python as well as sql." )
except FutureWarning:
  print("this file is created but after a session end file is delete so first cerat file")

#3. Write a Python program that opens a file and handles a FileNotFoundError exception if the file does not exist.
try:
  with open("Exception-handling-Assignment.txt","r") as d:
    data=d.read()
    print(data)
except FileNotFoundError:
  print("file dose not exist")

#4. Write a Python program that prompts the user to input two numbers and raises a TypeError exception if the inputs are not numerical.
try:
  num1=int(input("enter first a number: "))
  num2=int(input("enter secon number:" ))
  if num1>num2:
    print("num1 is greater than num2")
  else:
    print("num2 is greater than num1")
except ValueError:
  raise TypeError ("the entered numbers are not numerical")

try:
  try:
    num1=int(input("Enter a first number:  "))
    num2=int(input("Entre a second number: "))
  except ValueError:
    raise TypeError("The entered numbers are not numerical")
    if num1>num2:
      print("number 1 is gerater:")
    else:
      print("number 2 is greater:")
except TypeError as d:
  print(d)

#5. Write a Python program that opens a file and handles a PermissionError exception if there is a permission issue.
try:
    with open("Exception-handling-Assignment.txt","r") as d:
        data=d.read()
        print(data)
except PermissionError:
     print("if file don't open it needs permission from owner.")

# 6.Write a Python program that executes an operation on a list and handles an IndexError exception if the index is out of range.
try:
  lst=[1,2,3,4,5]
  print(lst[7])
  x=lst.pop(7)
except IndexError:
  print("Index is out of range")

#7.Write a Python program that executes division and handles an ArithmeticError exception if there is an arithmetic error.
try:

  def div(x,y):
    return x/y

  print(div(12,12))
except ArithmeticError :
  print("There is a error")