# -*- coding: utf-8 -*-
"""File_Io.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeIKLs0C8qV5B2OPyjKduPhPj9gJWN82
"""

#1. Write a Python program to read an entire text file.
d=open("File-IO-Assignment.txt",'r')
data=d.read()
print(data)
d.close()

#2. Write a Python program to read first n lines of a file.
d=open("File-IO-Assignment.txt",'r')
n=int(input("Entre nuber of line: "))
count=0
for i in d:
  print(i,end="")
  count+=1
  if count==n:
    break
d.close()

#3. Write a Python program to append text to a file and display the text.
d=open("File-IO-Assignment.txt",'a')
d.write("\n16.how to append a file in pycharm")

d.close()

d=open("File-IO-Assignment.txt")
data=d.read()
print(data)
d.close()

#4. Write a Python program to read last n lines of a file.
n=int(input("Enter number of lines: "))
d=open("File-IO-Assignment.txt",'r')
for line in (d.readlines()[-n:]):
  print(line,end="")
d.close()

#5. Write a Python program to read a file line by line and store it into a list.
d=open("File-IO-Assignment.txt","r")
lst=[]
for i in (d.readlines()):
  lst.append(i)
print(lst)
d.close()

#6. Write a Python program to read a file line by line store it into a variable.
d=open("File-IO-Assignment.txt","r")
v=[]
for i in (d.readlines()):
  v.append(i)
print(v)
d.close()

d=open("File-IO-Assignment.txt","r")
v=d.readlines()
print(v)
d.close()

#7. Write a python program to find the longest words.
d=open("File-IO-Assignment.txt","r")
data=d.read()
words=data.split()
max_lenght=0
for i in words:
  if len(i)>max_lenght:
    max_lenght=len(i)

for i in words:
  if len(i)==max_lenght:
    print(i)
d.close()

#8. Write a Python program to count the number of lines in a text file.
d=open("File-IO-Assignment.txt","r")
count=0
for i in d.readlines():
  count+=1
print(count)
d.close()

d=open("File-IO-Assignment.txt","r")
count=len(d.readlines())
print(count)
d.close()

#9. Write a Python program to count the frequency of words in a file.
d=open("File-IO-Assignment.txt","r")
data=d.read()
words=data.split()
di={}
for i in words:
  if i in di:
    di[i]=di[i]+1
  else:
    di[i]=1
print(di)
d.close()

#10. Write a Python program to get the file size of a plain file.
filename = input("Enter file name: ")
try:
  with open (filename,'r') as d:
    data=d.read()
    size=len(data)
    print("File size: ",size,"bytes")
except FileNotFoundError:
  print("File dose not exits")

from os import write
#11. Write a Python program to write a list to a file.
list1=[ 'Write' ,  'a'  , 'Python' , 'program' , 'to' , 'write' , 'a' , 'list' , 'to' , 'a' , 'file']
d=open("list_to_file",'w')
data=d.writelines(list1)

d.close()

try:
  with open("list_to_file",'r') as a:
    data=a.read()
    print(data)
except FileNotFoundError:
  print("File is not a found")
a.close()

#12. Write a Python program to copy the contents of a file to another file .
try:
    with open("list_to_file",'r') as d:
        data=d.read()
    with open("list_to_file1",'w') as f:
        f.write(data)
except FileExistsError:
    print("file dose not exists")

#13. Write a Python program to read a random line from a file.
import random
filename=input("Enter a file name: ")
try:
  with open(filename,'r') as d:
    lines=d.readlines()
    if len(lines)==0:
      print("File is empty")
    else:
      random_line=random.choice(lines)
      print("Random line: ",random_line.strip())
except FileNotFoundError:
  print("file dose not exists")

#14. Write a Python program to assess if a file is closed or not.
file = open("File-IO-Assignment.txt","r")
print("Before closing : ",file.close)
file.close()
print("After closing:", file.closed)

#15.Write a Python program that takes a text file as input and returns the number of words of a given text file. give me code
try:
  file = open("File1-IO-Assignment.txt","r")

  data=file.read()
  words=data.split()

  count =len(words)

  print("Number of words: ", count)
  #file.close()

except FileNotFoundError:
  print("File not found")