# -*- coding: utf-8 -*-
"""FunctionAssignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKQ3O9xO_3vdTRKUpTPQ-toNOKDyEEOg
"""

#1. Write a Python function to find the maximum of three numbers.
num=[44,55,77]
print(max(num))

def max_of_three(arr):
  if not arr:
    return "list Is emplty"
  maximum_num=arr[0]
  for i in arr:
    if i>maximum_num:
      maximum_num=i
  return maximum_num
my_arr=[44,55,77,89]
result=max_of_three(my_arr)
print(result)

#Write a Python function to sum all the numbers in a list.
num=(8,2,3,0,7)
count=0
for i in num:
  count=count+i
print(count)


def sum(list):
  total=0
  for i in list:
    total+=i
  return total

my_list=[8,2,3,0,7]
result=sum(my_list)
print(result)

# Write a Python function to multiply all the numbers in a list.
num=(8,2,3,-1,7)
count=1
for i in num:
  count=count*i
print(count)

def mul(list):
  count=1
  for i in list:
    count=count*i
  return count

my_list=[8,2,3,-1,7]
re=mul(my_list)
print(re)

#Write a Python function to reverse a string.
def reve(sample_str):
  sample_str=sample_str[::-1]
  return sample_str

sample_str=reve("1234abcd")
print(sample_str)

sample_string="1234abcd"
for i in sample_string[: : -1]:

    print(i,end=" ")

#Write a Python function to check whether a number falls within a given range.
num=4

if num >=1 and num<=10:
   print("Number is in a range")
else:
   print("Number is not in  a  range")

def fall_in(num,low,high):
  low=1
  high=10
  if num>=low and num<=high:
    print("Number is in range")
  else:
    print("Number is not in range")
num=4
re=fall_in(num,low,high)
print(re)

#Write a Python function that accepts a string and counts the number of upper and lower case letters.
def Accept_string(name):
    upper=0
    lower=0
    for i  in name:
        if i.isupper():
            upper+=1
        elif i.islower():
            lower+=1
    return upper, lower
name="The quick Brow Fox"
str1=Accept_string(name)
print(str1)

#Write a Python function that takes a list and returns a new list with distinct elements from the first list.
def distinct_list(list):
  new_list=[]
  for i in list:
    if i not in new_list:
      new_list.append(i)
  return new_list

li=[1,2,3,3,3,3,4,5]
list1=distinct_list(li)
print(list1)

#Write a Python function that checks whether a passed string is a palindrome or not.
def pali_string(strings):
  if strings==strings[::-1]:
    print("String is palindrome")
  else:
    print("String is not palidrome")

str= "madam"
pal=pali_string(str)
print(pal)

#Write a Python program that accepts a hyphen-separated sequence of words as input and prints the words in a hyphen-separated sequence after sorting them alphabetically.
def hype_sep(my_str):
  words= my_str.split("-")
  words.sort()
  return "-".join(words)

words="green-red-yellow-black-white"
print(hype_sep(words))

#Write a Python program to detect the number of local variables declared in a function.
def local_global():
  name="dipali",
  age=23,
  salary=100000

  print(locals())
  print(len(locals()))


local_global()

#11.Write a Python program to create a lambda function that adds 15 to a given number passed in as an argument, also create a lambda function that multiplies argument x with argument y and prints the result.
sum=lambda num: num+15
addition=sum(10)
print(addition)

mul=lambda num1,num2: num1*num2
multiply=mul(6,8)
print(multiply)

lst=[-1,10,-20,30,-20,50]
positive_num=filter(lambda num:num>0 ,lst )
print(list(positive_num))

#12.Write a Python program to create a function that takes one argument, and that argument will be multiplied with an unknown given number.
def mul(n):
  return lambda x:x*n
double = mul(2)
#triple=mul(3)
#quadral=mul(4)
#quintuple=mul(5)

print("Double the number of 15 =", double(15))
#print("Triple the number of 15 = ",triple(15))
#print("Quadral the number of 15 =", quadral(15))
#print("quintuple the number of 15 = ", quintuple(15))

#13.Write a Python program to sort a list of tuples using Lambda.
original_list=[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
sorting_list=sorted( original_list, key=lambda x:x[1])
print(sorting_list)

students = [('Amit', 70), ('Riya', 85), ('John', 60)]
sorte_list=sorted(students ,key=lambda x:x[1])
print(sorte_list)

data = [('A', 20, 80), ('B', 18, 90), ('C', 22, 70)]
sorted_list=sorted(data , key=lambda y:y[2])
print(sorted_list)

#14.Write a Python program to sort a list of dictionaries using Lambda.
original_list=[{'make': 'Nokia', 'model': 216, 'color': 'Black'}, {'make': 'Mi Max', 'model': '2', 'color': 'Gold'}, {'make': 'Samsung', 'model': 7, 'color': 'Blue'}]
sorted_lst=sorted(original_list , key=lambda x: x['color'])
print(sorted_lst)

#15.Write a Python program to filter a list of integers using Lambda.
ori_list=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

even_number=filter(lambda x: x%2==0 ,ori_list)
print("Even numbers from the list: ",list(even_number))

odd_number=filter(lambda x: x%2!=0 ,ori_list)
print("Odd number from the list: ",list(odd_number))

#16.Write a Python program to square and cube every number in a given list of integers using Lambda.
original_list=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

squre_list=map(lambda x : x*x,original_list)
print("Square every number of the said list:",list(squre_list))

cube_list=map(lambda x : x*x*x,original_list)
print("Cube of every number of the said list: ",list(cube_list))

#17. Write a Python program to find if a given string starts with a given character using Lambda.
string="Dipai"
given_char="D"
find_string=lambda x: x[0]==given_char
print(find_string(string))

#using startwith
string="diPLI"
CHECK="d"
print(string.startswith(CHECK))

#18.Write a Python program to rearrange positive and negative numbers in a given array using Lambda.
original_list=[-1, 2, -3, 5, 7, 8, 9, -10]
positive_list=list(filter(lambda x : x>0  , original_list))
negative_list=list(filter(lambda x : x<0  , original_list))
result=positive_list + negative_list
print(result)

#19.Write a Python program to count the even and odd numbers in a given array of integers using Lambda.
original_list=[1, 2, 3, 5, 7, 8, 9, 10]

even_number=len(list(filter( lambda x : x%2==0, original_list)))
print("number of even number in the above array:",even_number)

odd_number=len(list(filter(lambda x : x%2!=0 , original_list)))
print("Number of odd nubers in the above array: ",odd_number)

#20. Write a Python program to find numbers divisible by nineteen or thirteen from a list of numbers using Lambda.
original_list=[19, 65, 57, 39, 152, 639, 121, 44, 90, 190]

divisibal_by_19=filter(lambda x: x%19==0 or x%13==0,original_list)
print(list(divisibal_by_19))

#21. Write a Python program to check whether a given string contains a capital letter, a lower case letter, a number and a minimum length using lambda.
str="DIpali99767"
upper_str=any(map(lambda x: x.isupper() ,str))
lower_str=any(map(lambda x: x.islower(),str))
check_digit=any(map(lambda x: x.isdigit(),str))
min_length=len(str)>=8
if upper_str and lower_str and check_digit and min_length:
  print(True)
else:
  print(False)