# -*- coding: utf-8 -*-
"""Oops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2PQ0ZozI2jueVmuP3pxN1_qXr1la0KX
"""

#1. Write a Python program to create a class representing a Circle. Include methods to calculate its area and perimeter.
class Circle :
    def __init__(self,radius):
        self.radius=radius
        #self.weight=weight

    def area(self):
        result=3.14*self.radius**2
        return result

    def perimeter(self):
        result_per=2*3.14*self.radius
        re=result_per%2*3.14
        return re

ar=Circle(19)
print(ar.area())
print(ar.perimeter())

#2. Write a Python program to create a person class. Include attributes like name, country and date of birth. Implement a method to determine the person's age.
from datetime import date
class person:
    def __init__(self,name , country,dob):
        self.name=name
        self.country=country
        self.dob=dob

    def calcutee_age(self):
        today = date.today()
        age= today.year-self.dob.year
        if today < date(today.year,self.dob.month,self.dob.day):
            age-=1
        return age

name=input("Enter your name: ")
country=input("Enter your country : ")

print("Enter your date of birth :")
year=int(input("year (yyyy) : "))
month=int(input("Month (MM) : "))
day=int(input("day (dd)"))

user_dob=date(year,month, day)


per=person(name , country,user_dob)
print("name of the per:",per.name)
print("country :" , per.country)
print("dob : ", per.dob)
print("age :" , per.calcutee_age())

#3. Write a Python program to create a calculator class. Include methods for basic arithmetic operations.
class Calculator:
    def __init__(self,a,b):
        self.a=a
        self.b=b

    def Addition(self):
        result=self.a+self.b
        return result

    def Subtraction(self):
        resul=self.a-self.b
        return resul

    def Multiplication(self):
        result=self.a*self.b
        return result


    def division(self):
        if self.b==0:
            print("Divide by zero can't be:")
        else:
            result=self.a/self.b
            return result


cal=Calculator(10,20)
print("Addition is :", cal.Addition())
print("Subtraction is: ",cal.Subtraction())
print("Multiplication is : ",cal.Multiplication())
print("Division is : ",cal.division())

#4. Write a Python program to create a class that represents a shape. Include methods to calculate its area and perimeter. Implement subclasses for different shapes like circle, triangle, and square.
import math
class Shape:
    def area(self):
        pass

    def perimeter(self):
        pass

class Circle(Shape):
    def __init__(self,radius):
        self.radius=radius

    def area(self):
        result=3.14*self.radius*self.radius
        return result

    def perimeter(self):
        result=2*3.14*self.radius
        return result

class Square(Shape):
    def __init__(self,side):
        self.side=side

    def area(self):
        result=self.side*self.side
        return result

    def perimeter(self):
        result=4*self.side
        return result

class Triangle(Shape):
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c

    def area(self):
        re=(self.a+self.b+self.c)/2
        result=2**(re*(re-self.a)*(re-self.b)*(re-self.c))
        return result

    def perimeter(self):
        result=self.a+self.b+self.c
        return  result

cir=Circle(12)
squ=Square(12)
tri=Triangle(12,3,2)

print("Circle of area:" ,cir.area())
print("Circle of perimeter: ",cir.perimeter())

print("Square of area: " ,squ.area())
print("Square if perimeter : " ,squ.perimeter())

print("Triangle of area: ",tri.area())
print("Triangle of perimeter: " ,tri.perimeter())

#5. Write a Python program to create a class representing a binary search tree. Include methods for inserting and searching for elements in the binary tree.
class Node:
    def __init__(self,data):
        self.data=data
        self.left=None
        self.right=None

class BinarySearchTree:
    def __init__(self):
        self.root=None

    def insert(self,data):
        if self.root is None:
            self.root=Node(data)
        else:
            self._insert(self.root,data)

    def _insert(self,node,data):
        if data < node.data:
            if node.left is None:
                node.left = Node(data)
            else:
                self._insert(node.left,data)

        elif data >node.data:
            if node.right is None:
                node.right = Node(data)
            else:
                self._insert(node.right,data)

    def search(self,data):
        return self._search(self.root,data)

    def _search(self,node,data):
        if node is None:
            return "Not Found"

        if node.data == data:
            return "Found"

        elif data < node.data:
            return self._search(node.left,data)

        else:
            return self._search(node.right,data)


bts=BinarySearchTree()

bts.insert(50)
bts.insert(20)
bts.insert(50)
bts.insert(60)
bts.insert(70)
bts.insert(80)
bts.insert(10)

print(bts.search(20))
print(bts.search(103))
from os import remove

#6. Write a Python program to create a class representing a stack data structure. Include methods for pushing and popping elements.
class Stack:
    def __init__(self):
        self.items=[]

    def push(self,value):
        self.items.append(value)
        print(value,"Pushed in the stack")

    def pop(self):
        if len(self.items)==0:
            print("Stack is empty")
        else:
            removed =self.items.pop()
            print(removed,"Popped from the stack")

stc=Stack()

stc.push(20)
stc.push(30)
stc.push(50)

stc.pop()
stc.pop()

#7. Write a Python program to create a class representing a linked list data structure. Include methods for displaying linked list data, inserting and deleting nodes.
class Node:
    def __init__(self,data):
        self.data=data
        self.next=None

class LinkedList:
    def __init__(self):
        self.head=None

    def insert(self,data):
        new_node=Node(data)
        if self.head is None:
            self.head=new_node
        else:
            temp=self.head

            while temp.next :
                temp =temp.next
            temp.next= new_node

    def display(self):
        temp= self.head
        while temp:
            print(temp.data, end=" -> ")
            temp = temp.next
        print("None")

    def delete(self, value):
        if self.head is None:
            print("List is empty")
            return

        if self.head.data == value:
            self.head = self.head.next
            return

        temp = self.head
        while temp.next:
            if temp.next.data == value:
                temp.next = temp.next.next
                return
            temp = temp.next

        print("Value not found")

link=LinkedList()
link.insert(90)
link.insert(10)
link.insert(80)
link.insert(70)
link.insert(60)
link.insert(40)
link.insert(30)

link.display()

link.delete(10)

link.display()

#8. Write a Python program to create a claBss representing a shopping cart. Include methods for adding and removing items, and calculating the total price.
class ShoppingCart:
    def __init__(self):
        self.cart=[]

    def Adding(self):
        name =input("Enter Product name: ")
        price=float(input("Enter Product Price: "))
        qty=int(input("Enter Quantity of Product: "))
        item=(name,price,qty)
        self.cart.append(item)

    def Remove(self):
        name=input("Enter name of product for Remove or delete:")
        for item in self.cart:
            if item[0] == name:
                self.cart.remove(item)
                print("Product removed:")
                return
        print("product name is ot in cart:")

    def Calculate_Price(self):
        total=0
        for item in self.cart:
            total+=item[1]*item[2]
        return total

    def display(self):
        for item in self.cart:
            print("Name:", item[0], "Price:", item[1], "Qty:", item[2])

shopping=ShoppingCart()

shopping.Adding()
shopping.Adding()
shopping.Adding()
shopping.Adding()
shopping.Adding()

shopping.display()

shopping.Remove()
shopping.display()

#9. Write a Python program to create a class representing a stack data structure. Include methods for pushing, popping and displaying elements.
class Stack:
    def __init__(self):
        self.items=[]

    def push(self,value):
        self.items.append(value)
        print(value,"Pushed in the stack")

    def pop(self):
        if len(self.items)==0:
            print("Stack is empty")
        else:
            removed =self.items.pop()
            print(removed,"Popped from the stack")

stc=Stack()

stc.push(20)
stc.push(30)
stc.push(50)

stc.pop()
stc.pop()

#10. Write a Python program to create a class representing a queue data structure. Include methods for enqueueing and dequeueing elements
class Queue:
    def __init__(self):
        self.queue=[]

    def insert(self):
        value=int(input("Enter value:"))
        self.queue.append(value)
        #return self.queue

    def Remove(self):
        if len(self.queue) ==0:
            print("Queue is empty")
        else:
            item=self.queue.pop(0)
            print("Removed: ",item)


    def dispaly(self):
        for item in self.queue:
            print(item)

que=Queue()

que.insert()
que.insert()
que.insert()
que.insert()
que.insert()

que.dispaly()

que.Remove()
que.dispaly()

#11. Write a Python program to create a class representing a bank. Include methods for managing customer accounts and transactions.
	#Create a Python class called BankAccount which represents a bank account, having as attributes: accountNumber (numeric type), name (name of the account owner as string type), balance.
	#Create a constructor with parameters: accountNumber, name, balance.
	#Create a Deposit() method which manages the deposit actions.
	#Create a Withdrawal() method which manages withdrawals actions.
	#Create an bankFees() method to apply the bank fees with a percentage of 5% of the balance account.
	#Create a display() method to display account details. Give the complete code for the BankAccount class.
class BankAccount:
    def __init__(self,accountNumber,name,balance):
        self.accountNumber=accountNumber
        self.name=name
        self.balance=balance

    def deposit(self,amount):
        if amount>0:
           self.balance+=amount
        return self.balance

    def Withdrawl(self,amount):
        if amount > 0 and amount <= self.balance:
            self.balance-=amount
            return self.balance
        else:
            print("Balance is insufficient")

    def bankFees(self):
        fee=self.balance*5/100
        self.balance=self.balance-fee
        return self.balance

    def dispaly(self):
        print("Account Number is: ",self.accountNumber)
        print("Name is : ",self.name)
        print("Balance is : ",self.balance)

bank=BankAccount(12,"dipali",2000)
bank.dispaly()
bank.deposit( 500)

bank.dispaly()
bank.Withdrawl(1000)

bank.dispaly()
bank.bankFees()

bank.dispaly()

#12.Build a flashcard using class in python. A flashcard is a card having information on both sides, which can be used as an aid in memoization. Flashcards usually have a question on one side and an answer on the other.
import random
class FlashCard:
    def __init__(self):
        self.fruit={
            "Apple":"red",
            "banana" : "Yellow",
            "Straeberry" :"Pink",
            "Mango": "Yellow",
            "BlueBerry": "Blue",
            "Chery":"Red",
            "RaspBerry":"Bright red"
        }

    def qize(self):
        fruit,color=random.choice(list(self.fruit.items()))
        print("What is the color of Fruit: ", fruit)
        ans=input()

        if ans.lower()==color.lower():
            print("Correct Answer")
        else:
            print("wrong Answer")
            print("correct color is:  ",color)


print("welcome to fruit quize")
flash=FlashCard()

while True:
    flash.qize()
    choice = input("Enter 0, if you want to play again: ")

    if choice !="0":
        break

#13. TechWorld, a technology training center, wants to allocate courses for instructors. An instructor is identified by name, technology skills, experience and average feedback. An instructor is allocated a course, if he/she satisfies the below two conditions:
class Instructor:
    def __init__(self,name,techanology_Skills, experience,average_feedback):
        self.__name=name
        self.__techanology_Skills=techanology_Skills
        self.__experience=experience
        self.__average_feedback=average_feedback

    def set_name(self,name):
        self.__name=name

    def set_techanology_Skills(self,Skills):
        self.__techanology_Skills=Skills

    def set_experience(self,experience):
        self.__experience=experience

    def set_average_feedback(self,feedack):
        self.__average_feedback=feedack

    def check_eligibility(self):
        if self.__experience >3:
            if self.__average_feedback>=4.5:
                return True

        elif self.__experience<=3:
            if self.__average_feedback>=4:
                return True

        return  False

    def Allocated_course(self,technology):
        if self.check_eligibility():
           if  technology in self.__techanology_Skills:
               return True
           else:
               return False
        else:
            return False

ins=Instructor("Dipali",["Pyhton ","c"],4,4.6)
print(ins.check_eligibility())
print(ins.Allocated_course(["python","c"]))

#14. Write a program that uses datetime module within a class. Enter manufacturing date and expiry date of the product. The program must display the years, months and days that are left for expiry.
from  datetime import datetime

class Product:
    def __init__(self):
        self.manufacturing_date=None
        self.expiry_date=None

    def get_dates(self):
        mfg=input("Enter manufacturing date:(dd-mm-yyyy) ")
        expi=input("Enter expiry_date: (dd-mm-yyyy)")

        self.manufacturing_date=datetime.strptime(mfg ,"%d-%m-%Y")
        self.expiry_date=datetime.strptime(expi,"%d-%m-%Y")

    def check_expiry(self):
        today = datetime.today()
        diff = self.expiry_date -today

        days= diff.days

        years = days //365
        remaining = days%365
        months = remaining//30
        days  = remaining %30

        print("This time left for expiry: ")
        print("Years :",years)
        print("Moths : ",months)
        print("Days : ",days)

p=Product()
p.get_dates()
p.check_expiry()

#15. A university wants to automate their admission process. Students are admitted based on the marks scored in the qualifying exam. A student is identified by student id, age and marks in qualifying exam. Data are valid, if:
class Student:
    def __init__(self):
        self.__student_id=None
        self.__age=0
        self.__marks=0

    def set_student_id(self,student_id):
        self.__student_id=student_id
        #return student_id

    def set_age(self,age):
        self.__age=age
        #return age

    def set_marks(self,marks):
        self.__marks=marks
        #return marks

    def datavalid(self):
        if self.__age>20 :
            if self.__marks >0 and self.__marks<=100:
                return True
            return False
        else:
            print("Marks and age is invalid: ")


    def Admission(self):
        if self.datavalid():
            if self.__marks >= 65:
                return True
            else:
                return False
        else:
            return False

stud=Student()
stud.set_student_id(101)
stud.set_age(21)
stud.set_marks(75)

print("Valid data: ",stud.datavalid())
print("Admission: ",stud.Admission())

#16.Ice-Cream Scoops and Bowl shop
#Create a class Scoop which has one public property flavor and one private proptery price. Take flavor values during object creation.
class scoop:
  scoop_count=0
  def __init__(self,flavor):
    self.flavor=flavor
    self.__price=0
    scoop.scoop_count+=1

  def set_price(self,price):
    self.__price=price

  def get_price(self):
    return self.__price

  @classmethod
  def sold(cls):
      print("Total Scope Sold",cls.scoop_count)

class Bowl:
    bowl_count=0

    def __init__(self):
      self.__scoop_list=[]
      Bowl.bowl_count+=1

    def add_scoops(self, *scoops):
        for scoop in scoops:
          self.__scoop_list.append(scoop)

    def display(self):
        total = 0
        for scoop in self.__scoop_list:
            print("Flavor:", scoop.flavor, "Price:", scoop.get_price())
            total += scoop.get_price()
        print("Total Price:", total)

    @classmethod
    def sold(cls):
        print("Bowls sold:", cls.bowl_count)


s1 = scoop("Chocolate")
s1.set_price(50)

s2 = scoop("Vanilla")
s2.set_price(40)

s3 = scoop("Mango")
s3.set_price(60)


b = Bowl()
b.add_scoops(s1, s2, s3)

b.display()

scoop.sold()
Bowl.sold()

#17. Create a Bus child class that inherits from the Vehicle class. The default fare charge of any vehicle is seating capacity * 100. If Vehicle is Bus instance, we need to add an extra 10% on full fare as a maintenance charge. So total fare for bus instance will become the final amount = total fare + 10% of the total fare.
class Vehicle:
  def __init__(self, name, mileage, capacity):
    self.name = name
    self.mileage = mileage
    self.capacity =capacity

  def fare(self):
    fare=self.capacity*100
    return fare

class Bus(Vehicle):
  def fare(self):
    maintenance=super().fare()
    maintenance+=maintenance*10/100
    return maintenance
bus=Bus("School bus",12,50)
print("Total fare is: ",bus.fare())

#18. Write a Python class Employee with attributes like emp_id, emp_name, emp_salary, and emp_department and methods like calculate_emp_salary, emp_assign_department, and print_employee_details.

class Employee:
  def __init__(self,emp_id,emp_name,emp_salary,emp_department):
    self.emp_id=emp_id
    self.emp_name=emp_name
    self.emp_salary=emp_salary
    self.emp_department=emp_department

  def Change_Employee_department(self,new_departmet):
    self.emp_department=new_departmet
    #return new_departmet

  def print_employee_details(self):
    print("Employee id:  ",self.emp_id)
    print("Employee name : ",self.emp_name)
    print("Employee salary :", self.emp_salary)
    print("Employee department : ",self.emp_department)

  def calculate_emp_salary(self, salary, hours_worked):
        if hours_worked > 50:
            overtime = hours_worked - 50
            overtime_amount = overtime * (salary / 50)
            final_salary = salary + overtime_amount
        else:
            final_salary = salary
        return final_salary


emp=Employee("E7876","ADAMS",50000,"ACCOUNTING")
#print(emp.print_employee_details())
print(emp.Change_Employee_department("Banking"))
#print(emp.print_employee_details())
salary=emp.calculate_emp_salary(200000,55)
print("Final Salary:",salary)
emp.print_employee_details()

#19. Write a Python class Restaurant with attributes like menu_items, book_table, and customer_orders, and methods like add_item_to_menu, book_tables, and customer_order.

class Restaurant:
  def __init__(self):
    self.menu_item={}
    self.book_table=[]
    self.customer_orders=[]

  def add_item_to_menu(self,price,item_name):
    self.menu_item[item_name]=price
    #return self.menu_item

  def book_tables(self,table_number):
    self.book_table.append(table_number)
    #return self.book_table

  def customer_order(self,item_name):
    self.customer_orders.append(item_name)
    #return self.customer_order

  def menu(self):
    for item,price in self.menu_item.items():
      print (item , price)

  def table_reservation(self):
    for table in self.book_table:
      print(table)

  def print_customer_orders(self):
    for order in self.customer_orders:
      print(order)

res = Restaurant()

res.add_item_to_menu("pizza",250)
res.add_item_to_menu("burger",250)

res.customer_order("pizza")
res.customer_order("burger")

res.book_tables(1)
res.book_tables(3)

res.menu()
res.table_reservation()
res.print_customer_orders()

#20. Write a Python class BankAccount with attributes like account_number, balance, date_of_opening and customer_name, and methods like deposit, withdraw, and check_balance.
class BankAccount:
  def __init__(self,account_number,balance,date_of_opening,customer_name):
    self.account_number=account_number
    self.balance=balance
    self.date_of_opening=date_of_opening
    self.customer_name=customer_name

  def deposite(self,amount):
    balance=self.balance+amount
    return balance

  def withdraw(self,amount):
    if amount<0 and amount>self.balance:
      print("Insuuficient balance")
    else:
      balance=self.balance-amount
      return balance

  def check_balance(self):
    return self.balance

Bank=BankAccount("AX10",200000,"10-01-2025","Dipali")
print(Bank.check_balance())

Bank.deposite(1000)
Bank.balance=Bank.deposite(1000)
print(Bank.check_balance())

Bank.balance=Bank.withdraw(1000)
print(Bank.check_balance())

#21. Write a Python class Inventory with attributes like item_id, item_name, stock_count, and price, and methods like add_item, update_item, and check_item_details.

class Inventory:
  def __init__(self):
    self.inventory={}

  def add_item(self, item_id, item_name, stock_count, price):
        self.inventory[item_id] = [item_name, stock_count, price]

  def update_item(self, item_id, item_name, stock_count, price):
        if item_id in self.inventory:
            self.inventory[item_id][0] = item_name
            self.inventory[item_id][1] = stock_count
            self.inventory[item_id][2] = price
        else:
            print("Item not found")

  def check_item_details(self, item_id):
        if item_id in self.inventory:
            item = self.inventory[item_id]
            print("Item ID:", item_id)
            print("Item Name:", item[0])
            print("Stock:", item[1])
            print("Price:", item[2])
        else:
            print("Item not found")

inv = Inventory()

inv.add_item(101, "Pen", 50, 10)
inv.add_item(102, "Book", 20, 100)

inv.update_item(101, "Pen", 100, 12)

inv.check_item_details(101)