# -*- coding: utf-8 -*-
"""PyhtonChallenges.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VO9MEmSXvbMUCSTZgF3TBLTgRrCRQIyS
"""

#1.Challenge: Student Marks Analyzer
Student_data={}
while True:
  Student_name=input("enter a student name: ")
  if Student_name in Student_data:
     print("duplicate not allowed")
     continue

  Student_Marks=int(input("Enter student marks: "))
  Student_data[Student_name]=Student_Marks
  print(Student_data)

  choice = input("Add Another student? (yes/no)")
  if choice.lower()=="no":
      break
  elif choice.lower()=="yes":
      continue
  else:
    print("Invalid choice")
    break

print("Student Marks Analyzer")

total_student=len(Student_data)
print("total number of student is: ",total_student)

total=sum(Student_data.values())
average=total/total_student
print("average marks of student is : ",average)

highest=max(Student_data.values())
lowest=min(Student_data.values())

for name , marks in Student_data.items():
  if marks==highest:
    print("Highest marks scores: ",name)

for name , marks in Student_data.items():
  if marks==lowest:
    print("Lowest marks score is: ",name)


print("Height marks is :",highest)
print("Lowest marks is : ",lowest)

#2.Challenge: CLI Contact Book (CSV-Powered)
import csv
filename = "contact.csv"
try:
  with open("contact.csv","w") as d:
    writer = csv.writer(d)
    writer.writerow(["Name","Phone","Email"])
    print("File created")
except FileExistsError:
  pass

while True:
  print("\n Menu")
  choice = input("""
1.Add Contact
2.View All Contact
3.Search Contact
4.Exit
Enter choice: """)

  if choice=="1":
    name= input("Enter Name: ")
    phone=input("Enter Phone number: ")
    email=input("Enter your Email : ")

    with open(filename,"a",newline="") as file:
      writer = csv.writer(file)
      writer.writerow([name ,phone , email])
    print("Ci=ontact Added")

  elif choice=="2":
    with open(filename , "r") as file:
        reader=csv.reader(file)
        for i in reader:
          print(i)

  elif choice=="3":
    search_contact=input("Entre name to search: ")
    found =False
    with open(filename , "r") as file:
        reader=csv.reader(file)
        for i in reader:
          if search_contact.lower()in i[0].lower():
            print("found : ",i)
            found =True

    if not found:
        print("Contact not found")

  elif choice=="4":
   print("Program Exist:")
   break
  else:
    print("Invalid choice")

#3 chllenges: personal movie tracker with json.
import json
from importlib import reload
reload(json)

filename="Movies.json"

if not os.path.exists(filename):
  with open("Movies.json","w") as d:
    json.dump=[], d

while True:
    print("\nMenu")
    choice = input("""
1. Add Movie
2. View Movies
3. Search Movie
4. Exit
""")

    if choice=="1":
      title=input("Enter Movie Title: ")
      genre=input("Enter Movie Genere: ")
      rating=input("Enter Movie Rating: ")

      try:
         with open(filename,"r") as file:
           movies=json.load(file)
      except:
         movies=[]
      for movie in movies:
         if movie["title"].lower()==title.lower():
            print("Movie is already exists:")
            break
      else:
         new_movie={
           "title":title,
           "genre":genre,
           "rating":rating
        }
         movies.append(new_movie)

         with open(filename ,"w") as file:
           json.dump(movies, file, indent=4)
         print("Movie is added")

    elif choice == "2":
       with open(filename,"r")as file:
         data=json.load(file)
       if len(data) ==0:
        print("No Movies Found")
       else:
        for d in data:
          print(d)

    elif choice == "3":
     search_movie = input("Enter movie name to search: ")
     found = False

     with open(filename, "r") as file:
        data = json.load(file)

        for d in data:
            if search_movie.lower() in d["title"].lower():
                print("Found:", d)
                found = True

        if not found:
            print("Movie not found")

    elif choice=="4":
      print("Program Exist:")
      break
    else:
      print("Invalid choice")

#4.Challenges: real-time weather logger (API+csv)
import requests
import csv
import os
from datetime import datetime
from collections import Counter

API_KEY = "ef9ae6527b22b754d0ba71feb8397ef1"
FILE_NAME = "weather_log.csv"


# Create CSV if not exists
def create_file():
    if not os.path.exists(FILE_NAME):
        with open(FILE_NAME, "w", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(["Date", "City", "Temperature", "Condition"])


# Fetch weather from API
def get_weather(city):
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

    try:
        response = requests.get(url)
        data = response.json()

        if data["cod"] != 200:
            print("Invalid city name!")
            return None

        temp = data["main"]["temp"]
        condition = data["weather"][0]["main"]

        return temp, condition

    except:
        print("API Error!")
        return None


# Check duplicate entry
def is_duplicate(date, city):
    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)
        next(reader)

        for row in reader:
            if row[0] == date and row[1].lower() == city.lower():
                return True
    return False


# Add new weather log
def add_log():
    city = input("Enter city: ")
    today = datetime.now().strftime("%Y-%m-%d")

    if is_duplicate(today, city):
        print("Entry already exists for today!")
        return

    weather = get_weather(city)

    if weather:
        temp, condition = weather

        with open(FILE_NAME, "a", newline="") as file:
            writer = csv.writer(file)
            writer.writerow([today, city, temp, condition])

        print("Weather logged successfully!")


# View all logs
def view_logs():
    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)

        print("\nDate        City        Temp(C)     Condition")
        print("-" * 50)

        for row in reader:
            print(f"{row[0]:<12}{row[1]:<12}{row[2]:<12}{row[3]}")


# Show statistics
def show_stats():
    temps = []
    conditions = []

    with open(FILE_NAME, "r") as file:
        reader = csv.reader(file)
        next(reader)

        for row in reader:
            temps.append(float(row[2]))
            conditions.append(row[3])

    if not temps:
        print("No data available")
        return

    print("\nWeather Statistics")
    print("------------------")
    print("Average Temp:", round(sum(temps) / len(temps), 2))
    print("Highest Temp:", max(temps))
    print("Lowest Temp:", min(temps))

    most_common = Counter(conditions).most_common(1)[0][0]
    print("Most Frequent Condition:", most_common)


# Menu
def menu():
    create_file()

    while True:
        print("\nWeather Logger")
        print("1. Add Weather Log")
        print("2. View All Logs")
        print("3. Show Statistics")
        print("4. Exit")

        choice = input("Enter choice: ")

        if choice == "1":
            add_log()

        elif choice == "2":
            view_logs()

        elif choice == "3":
            show_stats()

        elif choice == "4":
            print("Goodbye!")
            break

        else:
            print("Invalid choice")


menu()